// @ts-check
// 사이드바: docs 폴더 구조를 그대로 따라감 (폴더 = 카테고리)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
