// @ts-check
// Sidebar auto-generated from the docs folder structure (folder = category)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
